apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
spec:
  ports:
  - name: api
    port: 8080
    protocol: TCP
    targetPort: {{ .Values.port }}
  selector:
    app: {{ .Chart.Name }}
  type: ClusterIP
