name: Go unit tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
      - name: Check gofmt compliant
        run: |
          cd src
          if [[ $(gofmt -l .) ]]; then
              echo "Files not gofmt compliant:"
              gofmt -l .
              exit 1
          else
              exit 0
          fi
      - name: Install dependencies
        run: |
          cd src
          go get .
      - name: Test with Go
        run: |
          cd src
          go test -v
